[build.environment]
NODE_VERSION = "20.12.2"
YARN_VERSION = "1.22.4"

[build]
  command = "yarn install --frozen-lockfile && yarn build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "/scripts/zulip-notification"
