[build.environment]
NODE_VERSION = "20.12.0"
YARN_VERSION = "1.22.4"

[build]
  command = "yarn build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "/scripts/zulip-notification"
