[build.environment]
     NODE_VERSION = "20.12.0"

[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "/scripts/zulip-notification"
