// index.js

const url = require('url')
const axios = require('axios')

module.exports = {
  onSuccess: async ({ constants, packageJson, netlifyConfig }) => {
    console.log('Zulip notification of on Success')
    const environment = netlifyConfig.build.environment
    const pullBranch = process.env.BRANCH
    const deployUrl = environment.DEPLOY_PRIME_URL
    const branchName = environment.BRANCH
    // console.log(process.env)
    const token = process.env.ZULIP_TOKEN
    const name = packageJson.name
    const version = packageJson.version
    const user = 'netlify-bot@unfoldingword.zulipchat.com'
    const appName = `${name} v${version}`
    const content = `${appName} for branch ${branchName} generated by ${pullBranch}, successfully published at ${deployUrl}`
    console.log(content)

    try {
      // const token_ = Buffer.from(`${user}:${token}`, 'utf8').toString('base64')

      const data = {
        to:       'SOFTWARE - UR/github',
        subject:  `${appName} - ${branchName}`,
        content,
        type:     'stream',
      }
      console.log({ data })
      const params = new url.URLSearchParams(data)

      await axios.post('https://unfoldingword.zulipchat.com/api/v1/messages',
        params.toString(),
        {
          auth: {
            username: user,
            password: token,
          },
        })
    } catch (error) {
      console.error('error Sending Zulip notification', error)
    }
  }
}
