name: Run Cypress and Jest Tests

on: [push, pull_request]

env:
  CHILD_CONCURRENCY: 1
  NODE_ENV: test
  CYPRESS_TEST_USERNAME: ${{ secrets.CYPRESS_TEST_USERNAME }}
  CYPRESS_TEST_PASSWORD: ${{ secrets.CYPRESS_TEST_PASSWORD }}
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
jobs:
  tests-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.12.2]
    steps:
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          headless: true
          record: true
          build: yarn build
          start: yarn start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 360
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      - name: Save Cypress Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Cypress Videos
          path: ./cypress/videos/
      - name: Cypress Coverage Summary
        run: yarn coverage-summary
      # run unit tests
      - name: Run Jest Unit Tests
        run: yarn test:unit
      # Combine test coverage reports
      - name: Combine Cypress & Jest coverage reports
        run: yarn report:combined
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: ./coverage/lcov.info

  upload-to-codecov:
    needs: [tests-run]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
