name: Cypress Tests

on: [push, pull_request]

env:
  CHILD_CONCURRENCY: 1
  NODE_ENV: test
  CYPRESS_TEST_USERNAME: ${{ secrets.CYPRESS_TEST_USERNAME }}
  CYPRESS_TEST_PASSWORD: ${{ secrets.CYPRESS_TEST_PASSWORD }}
jobs:
  cypress-run:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [12.13.0]
    steps:
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      - name: Yarn setup
        run: yarn
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          headless: true
          build: yarn build
          start: yarn start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 360
      - name: Save Cypress Videos
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Cypress Videos
          path: ./cypress/videos/
