name: Run Cypress and Jest Tests

on: [push, pull_request]

env:
  CHILD_CONCURRENCY: 1
  NODE_ENV: test
  CYPRESS_TEST_USERNAME: ${{ secrets.CYPRESS_TEST_USERNAME }}
  CYPRESS_TEST_PASSWORD: ${{ secrets.CYPRESS_TEST_PASSWORD }}
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
jobs:
  tests-run:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [12.13.0]
    steps:
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          headless: true
          record: true
          build: yarn build
          start: yarn start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 360
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      - name: Save Cypress Videos
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Cypress Videos
          path: ./cypress/videos/
      - name: Cypress Coverage Summary
        run: yarn coverage-summary
      # run unit tests
      - name: Run Jest Unit Tests
        run: yarn test:unit
      # Combine test coverage reports
      - name: Combine Cypress & Jest coverage reports
        run: yarn report:combined
      # Upload combined test coverage report to Coveralls
      - name: Upload Combined coverage report to Coveralls
        run: yarn coveralls:upload
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
